server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO

jobrunr:
  background-job-server:
    enabled: true
  dashboard:
    enabled: true
    port: 8001
    username: ${JOB_RUNR_USERNAME}
    password: ${JOB_RUNR_PASSWORD}
  database:
    type: sql

spring:
  datasource:
    url: jdbc:h2:file:./data/test;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: sa

  jpa:
    open-in-view: false

telegram:
  telegram-url: ${TELEGRAM_URL}
  telegram-chat-id: ${TELEGRAM_CHAT_ID}
